name: ExpressionTreeComparer.CI
run-name: ExpressionTreeComparer.CI

on:
  push:
    paths: [ ./** ]
    branches: [ main, feature/* ]
  pull_request:
    paths: [ ./** ]
    branches: [ main, feature/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x.x'
    - name: Install dependencies
      run: dotnet restore ExpressionTreeComparer.csproj
    - name: Build
      run: dotnet build ExpressionTreeComparer --configuration Release --no-restore
    - name: Test
        run: dotnet test --no-restore --verbosity normal