name: ExpressionTreeComparer.CI
run-name: ExpressionTreeComparer.CI

on:
  push:
    branches: 
      - main
      - feature/*
  pull_request:
    branches: 
      - main
      - feature/*
  workflow_dispatch:
env:
  # folder containing the project to build.
  PROJECT_PATH: src/ExpressionTreeComparer
  # name of the csproj file to build (including extension)
  PROJECT_FILE_NAME: ExpressionTreeComparer.csproj
  # name of the csproj file to build (without extension)
  PROJECT_NAME: ExpressionTreeComparer
  # folder containing the unit test project.
  UNIT_TEST_PROJECT_PATH: src/ExpressionTreeComparer.UnitTests
  # name of the csproj file of the unit test project (without extension)
  UNIT_TEST_PROJECT_NAME: ExpressionTreeComparer.UnitTests
   # folder containing the integration test project.
  INTEG_TEST_PROJECT_PATH: src/ExpressionTreeComparer.IntegrationTests
  # name of the csproj file of the integration test project (without extension)
  INTEG_TEST_PROJECT_NAME: ExpressionTreeComparer.IntegrationTests
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x.x'

    - name: Install dependencies
      run: dotnet restore $PROJECT_PATH/$PROJECT_NAME.csproj

    - name: Build
      run: dotnet build $PROJECT_PATH/$PROJECT_NAME.csproj --configuration Release --no-restore --verbosity normal

    - name: "Unit Test"
      run: dotnet test $UNIT_TEST_PROJECT_PATH/$UNIT_TEST_PROJECT_NAME.csproj Release --no-restore --verbosity normal

    - name: "Integration Test"
      run: dotnet test $INTEG_TEST_PROJECT_PATH/$INTEG_TEST_PROJECT_NAME.csproj Release --no-restore --verbosity normal